import type { NavigationTree } from '@/@types/navigation'
import { urlConfig } from '@/configs/urls.config'
import { NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM, NAV_ITEM_TYPE_TITLE } from '@/constants/navigation.constant'
import { Role } from '@/enums/role.enum'

const appsNavigationConfig: NavigationTree[] = [
  {
    key: 'apps',
    path: '',
    title: '',
    translateKey: '',
    icon: 'apps',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: 'dashboard',
        path: urlConfig.dashboard,
        title: 'Dashboard',
        translateKey: '',
        icon: 'apps',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [
          Role.ADMIN,
          Role.MANAGER_AFF,
          Role.MANAGER_AGENCY,
          Role.MEMBER_AFF,
          Role.MEMBER_AGENCY,
          Role.ACCOUNTING,
        ],
        subMenu: [],
      },
      {
        key: 'taskManagement',
        path: '',
        title: 'Quản lý công việc',
        translateKey: '',
        icon: 'task',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
        subMenu: [
          {
            key: 'taskAssign',
            path: urlConfig.taskAssign,
            title: 'Giao việc',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
            subMenu: [],
          },
        ],
      },
      {
        key: 'projectManagement',
        path: '',
        title: 'Quản lý dự án',
        translateKey: '',
        icon: 'project',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [
          Role.ADMIN,
          Role.MANAGER_AFF,
          Role.MANAGER_AGENCY,
          Role.MEMBER_AFF,
          Role.MEMBER_AGENCY,
          Role.ACCOUNTING,
        ],
        subMenu: [
          {
            key: 'projects',
            path: urlConfig.projects,
            title: 'Dự án',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.ACCOUNTING],
            subMenu: [],
          },
          {
            key: 'campaigns',
            path: urlConfig.campaigns,
            title: 'Chiến dịch',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [
              Role.ADMIN,
              Role.MANAGER_AFF,
              Role.MANAGER_AGENCY,
              Role.MEMBER_AFF,
              Role.MEMBER_AGENCY,
              Role.ACCOUNTING,
            ],
            subMenu: [],
          },
          {
            key: 'finalUrls',
            path: urlConfig.finalUrls,
            title: 'URL',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [
              Role.ADMIN,
              Role.MANAGER_AFF,
              Role.MANAGER_AGENCY,
              Role.MEMBER_AFF,
              Role.MEMBER_AGENCY,
              Role.ACCOUNTING,
            ],
            subMenu: [],
          },
        ],
      },
      {
        key: 'gmailManagement',
        path: '',
        title: 'Quản lý Gmail',
        translateKey: '',
        icon: 'account',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [
          Role.ADMIN,
          Role.MANAGER_AFF,
          Role.MANAGER_AGENCY,
          Role.MEMBER_AFF,
          Role.MEMBER_AGENCY,
          Role.ACCOUNTING,
        ],
        subMenu: [
          {
            key: 'gmailAccounts',
            path: urlConfig.gmailAccounts,
            title: 'Tài khoản Gmail',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
            subMenu: [],
          },
        ],
      },
      {
        key: 'systems',
        path: '',
        title: 'Quản trị hệ thống',
        translateKey: '',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN],
        subMenu: [
          {
            key: 'users',
            path: urlConfig.users,
            title: 'Tài khoản',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: 'masterData',
        path: '',
        title: 'Quản lý Master Data',
        translateKey: '',
        icon: 'star',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN],
        subMenu: [
          {
            key: 'projectTypes',
            path: urlConfig.projectTypes,
            title: 'Loại dự án',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'projectStatus',
            path: urlConfig.projectStatus,
            title: 'Trạng thái dự án',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'uidStatus',
            path: urlConfig.uidStatus,
            title: 'Trạng thái UID',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
        ],
      },
    ],
  },
]

export default appsNavigationConfig
