import { NAV_ITEM_TYPE_TITLE, NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { urlConfig } from '@/configs/urls.config'
import { Role } from '@/enums/role.enum'

const appsNavigationConfig: NavigationTree[] = [
  {
    key: 'apps',
    path: '',
    title: '',
    translateKey: '',
    icon: 'apps',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: 'dashboard',
        path: urlConfig.dashboard,
        title: 'Dashboard',
        translateKey: '',
        icon: 'apps',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
        subMenu: [],
      },
      {
        key: 'tasks',
        path: '',
        title: 'Quản lý công việc',
        translateKey: '',
        icon: 'task',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
        subMenu: [
          {
            key: 'tasks.assign',
            path: urlConfig.taskAssign,
            title: 'Giao việc',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
            subMenu: [],
          },
          // {
          //   key: 'tasks.reports',
          //   path: urlConfig.taskReport,
          //   title: 'Báo cáo MAR',
          //   translateKey: '',
          //   icon: '',
          //   type: NAV_ITEM_TYPE_ITEM,
          //   authority: [Role.ADMIN, Role.USER],
          //   subMenu: [],
          // },
        ],
      },
      {
        key: 'projects',
        path: '',
        title: 'Quản lý dự án',
        translateKey: '',
        icon: 'project',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
        subMenu: [
          {
            key: 'projects.list',
            path: urlConfig.projects,
            title: 'Dự án',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY],
            subMenu: [],
          },
          {
            key: 'adsGroups',
            path: urlConfig.adsGroups,
            title: 'Nhóm tài khoản Ads',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
            subMenu: [],
          },
          {
            key: 'adsAccounts',
            path: urlConfig.adsAccounts,
            title: 'Tài khoản Ads',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.MANAGER_AFF, Role.MANAGER_AGENCY, Role.MEMBER_AFF, Role.MEMBER_AGENCY],
            subMenu: [],
          },
        ],
      },
      // {
      //   key: 'customers',
      //   path: '',
      //   title: 'Quản lý khách hàng',
      //   translateKey: '',
      //   icon: 'crm',
      //   type: NAV_ITEM_TYPE_COLLAPSE,
      //   authority: [Role.ADMIN, Role.USER],
      //   subMenu: [
      //     {
      //       key: 'customers.list',
      //       path: urlConfig.customerList,
      //       title: 'Khách hàng',
      //       translateKey: '',
      //       icon: '',
      //       type: NAV_ITEM_TYPE_ITEM,
      //       authority: [Role.ADMIN, Role.USER],
      //       subMenu: [],
      //     },
      //   ],
      // },
      // {
      //   key: 'finances',
      //   path: '',
      //   title: 'Quản lý tài chính',
      //   translateKey: '',
      //   icon: 'sales',
      //   type: NAV_ITEM_TYPE_COLLAPSE,
      //   authority: [Role.ADMIN, Role.USER],
      //   subMenu: [
      //     {
      //       key: 'sales',
      //       path: urlConfig.financeSales,
      //       title: 'Doanh số dự án',
      //       translateKey: '',
      //       icon: '',
      //       type: NAV_ITEM_TYPE_ITEM,
      //       authority: [Role.ADMIN, Role.USER],
      //       subMenu: [],
      //     },
      //     {
      //       key: 'reports',
      //       path: urlConfig.financeReport,
      //       title: 'Thống kê',
      //       translateKey: '',
      //       icon: '',
      //       type: NAV_ITEM_TYPE_ITEM,
      //       authority: [Role.ADMIN, Role.USER],
      //       subMenu: [],
      //     },
      //   ],
      // },
      {
        key: 'systems',
        path: '',
        title: 'Quản trị hệ thống',
        translateKey: '',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN],
        subMenu: [
          {
            key: 'users',
            path: urlConfig.users,
            title: 'Tài khoản',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          // {
          //   key: 'logs',
          //   path: urlConfig.logs,
          //   title: 'Thông báo',
          //   translateKey: '',
          //   icon: '',
          //   type: NAV_ITEM_TYPE_ITEM,
          //   authority: [Role.ADMIN],
          //   subMenu: [],
          // },
          // {
          //   key: 'setting',
          //   path: urlConfig.setting,
          //   title: 'Cấu hình hệ thống',
          //   translateKey: '',
          //   icon: '',
          //   type: NAV_ITEM_TYPE_ITEM,
          //   authority: [Role.ADMIN],
          //   subMenu: [],
          // },
        ],
      },
      // {
      //   key: 'staff',
      //   path: '',
      //   title: 'Quản lý nhân sự',
      //   translateKey: '',
      //   icon: 'account',
      //   type: NAV_ITEM_TYPE_COLLAPSE,
      //   authority: [Role.ADMIN, Role.USER],
      //   subMenu: [
      //     {
      //       key: 'rankings',
      //       path: urlConfig.staffRanking,
      //       title: 'Bảng xếp hạng',
      //       translateKey: '',
      //       icon: '',
      //       type: NAV_ITEM_TYPE_ITEM,
      //       authority: [Role.ADMIN, Role.USER],
      //       subMenu: [],
      //     },
      //   ],
      // },
    ],
  },
]

export default appsNavigationConfig
