import { NAV_ITEM_TYPE_TITLE, NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { urlConfig } from '@/configs/urls.config'
import { Role } from '@/enums/role.enum'

const appsNavigationConfig: NavigationTree[] = [
  {
    key: 'apps',
    path: '',
    title: '',
    translateKey: '',
    icon: 'apps',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: 'apps.dashboard',
        path: urlConfig.dashboard,
        title: 'Dashboard',
        translateKey: '',
        icon: 'apps',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [Role.ADMIN],
        subMenu: [],
      },
      {
        key: 'apps.tasks',
        path: '',
        title: 'Quản lý công việc',
        translateKey: '',
        icon: 'project',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.USER],
        subMenu: [
          {
            key: 'tasks.assign',
            path: urlConfig.taskAssign,
            title: 'Giao việc',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'tasks.reports',
            path: urlConfig.taskReport,
            title: 'Báo cáo MAR',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.USER],
            subMenu: [],
          },
        ],
      },
      {
        key: 'apps.customers',
        path: '',
        title: 'Quản lý khách hàng',
        translateKey: '',
        icon: 'crm',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.USER],
        subMenu: [
          {
            key: 'customers.list',
            path: urlConfig.customerList,
            title: 'Danh sách khách hàng',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.USER],
            subMenu: [],
          },
          {
            key: 'customers.update',
            path: urlConfig.customerUpdate,
            title: 'Cập nhật khách hàng',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.USER],
            subMenu: [],
          },
        ],
      },
      {
        key: 'apps.finances',
        path: '',
        title: 'Quản lý tài chính',
        translateKey: '',
        icon: 'sales',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.USER],
        subMenu: [
          {
            key: 'finances.sales',
            path: urlConfig.financeSales,
            title: 'Doanh số dự án',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.USER],
            subMenu: [],
          },
          {
            key: 'finances.reports',
            path: urlConfig.financeReport,
            title: 'Thống kê',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.USER],
            subMenu: [],
          },
        ],
      },
      {
        key: 'apps.systems',
        path: '',
        title: 'Quản trị hệ thống',
        translateKey: '',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN],
        subMenu: [
          {
            key: 'systems.users',
            path: urlConfig.systemUsers,
            title: 'Tài khoản',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'systems.adsGroups',
            path: urlConfig.systemAdsGroups,
            title: 'Nhóm tài khoản Ads',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'systems.projects',
            path: urlConfig.systemProjects,
            title: 'Dự án',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'system.logs',
            path: urlConfig.systemLogs,
            title: 'Thông báo',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
          {
            key: 'system.setting',
            path: urlConfig.systemSetting,
            title: 'Cấu hình hệ thống',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: 'apps.staff',
        path: '',
        title: 'Quản lý nhân sự',
        translateKey: '',
        icon: 'account',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [Role.ADMIN, Role.USER],
        subMenu: [
          {
            key: 'staff.rankings',
            path: urlConfig.staffRanking,
            title: 'Bảng xếp hạng',
            translateKey: '',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [Role.ADMIN, Role.USER],
            subMenu: [],
          },
        ],
      },
    ],
  },
]

export default appsNavigationConfig
