import { Link, useLocation } from 'react-router-dom'
import { HiChevronRight, HiHome } from 'react-icons/hi'

export interface BreadcrumbItem {
  label: string
  path?: string
}

interface BreadcrumbProps {
  items?: BreadcrumbItem[]
  separator?: React.ReactNode
  showHome?: boolean
  homeLabel?: string
  homePath?: string
  className?: string
}

export default function Breadcrumb({
  items = [],
  separator = <HiChevronRight className="text-gray-400" />,
  showHome = true,
  homeLabel = 'Trang chủ',
  homePath = '/dashboard',
  className = '',
}: BreadcrumbProps) {
  const location = useLocation()

  const autoGeneratedItems = items.length === 0 ? generateBreadcrumbFromPath(location.pathname) : items

  return (
    <nav className={`flex items-center space-x-2 text-sm ${className}`} aria-label="Breadcrumb">
      {showHome && (
        <>
          <Link
            to={homePath}
            className="flex items-center gap-1 text-gray-600 hover:text-gray-900 dark:hover:text-gray-200 dark:text-gray-400 transition-colors"
          >
            <HiHome className="text-lg" />
            <span>{homeLabel}</span>
          </Link>
          {autoGeneratedItems.length > 0 && <span className="text-gray-400">{separator}</span>}
        </>
      )}

      {autoGeneratedItems.map((item, index) => {
        const isLast = index === autoGeneratedItems.length - 1

        return (
          <div key={index} className="flex items-center space-x-2">
            {item.path && !isLast ? (
              <Link
                to={item.path}
                className="text-gray-600 hover:text-gray-900 dark:hover:text-gray-200 dark:text-gray-400 transition-colors"
              >
                {item.label}
              </Link>
            ) : (
              <span className="font-medium text-gray-900 dark:text-gray-100">{item.label}</span>
            )}
            {!isLast && <span className="text-gray-400">{separator}</span>}
          </div>
        )
      })}
    </nav>
  )
}

function generateBreadcrumbFromPath(pathname: string): BreadcrumbItem[] {
  const pathSegments = pathname.split('/').filter(Boolean)

  const breadcrumbs: BreadcrumbItem[] = []
  let currentPath = ''

  pathSegments.forEach((segment, index) => {
    currentPath += `/${segment}`

    const label = segment
      .replace(/[-_]/g, ' ')
      .split(' ')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ')

    breadcrumbs.push({
      label,
      path: index === pathSegments.length - 1 ? undefined : currentPath,
    })
  })

  return breadcrumbs
}
