import type { MetricCardConfig } from "@/modules/projectDailyStats/types/projectDailyMetrics.type";
import { Role } from "@/shared/constants/role.constant";
import { fixedNumber, formatDollarAmount } from "@/shared/utils/common.util";
import {
  Activity,
  BadgeDollarSign,
  Calculator,
  CheckCircle,
  DollarSign,
  MousePointerClick,
  Percent,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  Wallet,
} from "lucide-react";

export const projectDailyMetricsConfig: MetricCardConfig[] = [
  {
    key: "totalCost",
    label: "Tổng chi tiêu",
    format: (v) => formatDollarAmount(v),
    icon: DollarSign,
    color: "text-red-500",
  },
  {
    key: "totalClicks",
    label: "Tổng lượt click",
    icon: MousePointerClick,
    color: "text-blue-500",
  },
  {
    key: "avgCpc",
    label: "CPC trung bình",
    format: (v) => formatDollarAmount(v),
    icon: TrendingUp,
    color: "text-purple-500",
  },
  {
    key: "totalProfit",
    label: "Lợi nhuận",
    format: (v) => formatDollarAmount(v),
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: TrendingUp,
    color: "text-green-500",
  },
  {
    key: "avgRoi",
    label: "ROI trung bình",
    format: (v) => `${fixedNumber(v)}%`,
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Percent,
    color: "text-yellow-500",
  },
  {
    key: "totalHoldRevenue",
    label: "Hoa hồng tạm giữ",
    format: (v) => formatDollarAmount(v),
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Wallet,
    color: "text-orange-500",
  },
  {
    key: "totalReceivedRevenue",
    label: "Hoa hồng rút về",
    format: (v) => formatDollarAmount(v),
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: BadgeDollarSign,
    color: "text-emerald-500",
  },
  {
    key: "totalRef",
    label: "Tổng Ref",
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Users,
    color: "text-cyan-500",
  },
  {
    key: "avgCostPerRef",
    label: "Chi phí trung bình/Ref",
    format: (v) => formatDollarAmount(v),
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Calculator,
    color: "text-pink-500",
  },
  {
    key: "avgRateRefPerClick",
    label: "Tỷ lệ Ref/Click trung bình",
    format: (v) => `${fixedNumber(v)}%`,
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Percent,
    color: "text-teal-500",
  },
  {
    key: "totalFtd",
    label: "Tổng FTD",
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: UserCheck,
    color: "text-lime-500",
  },
  {
    key: "avgCostPerFtd",
    label: "Chi phí trung bình/FTD",
    format: (v) => formatDollarAmount(v),
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Calculator,
    color: "text-rose-500",
  },
  {
    key: "avgRateFtdPerRef",
    label: "Tỷ lệ FTD/Ref trung bình",
    format: (v) => `${fixedNumber(v)}%`,
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Percent,
    color: "text-violet-500",
  },
  {
    key: "totalTargetDailyKeyVolume",
    label: "Volume key/ngày ",
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Activity,
    color: "text-amber-500",
  },
  {
    key: "totalTargetRef",
    label: "Tổng mục tiêu Ref",
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: Target,
    color: "text-indigo-500",
  },
  {
    key: "avgClickAchievementRate",
    label: "Tỷ lệ hoàn thành Click trung bình",
    format: (v) => `${fixedNumber(v)}%`,
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: CheckCircle,
    color: "text-green-600",
  },
  {
    key: "avgRefAchievementRate",
    label: "Tỷ lệ hoàn thành Ref trung bình",
    format: (v) => `${fixedNumber(v)}%`,
    allowedRoles: [Role.ADMIN, Role.ACCOUNTING],
    icon: CheckCircle,
    color: "text-emerald-600",
  },
];
