export const COLUMN_CONFIG = [
  { id: 'stt', label: 'STT', visible: true, required: true },
  { id: 'date', label: 'Ngày', visible: true, required: true },
  { id: 'projectName', label: 'Tên dự án', visible: true, required: true },
  { id: 'projectStatus', label: 'Trạng thái dự án', visible: true, required: true },
  { id: 'profit', label: 'Lợi nhuận', visible: true, required: true },
  { id: 'roi', label: 'ROI (%)', visible: true, required: true },
  { id: 'holdRevenue', label: 'Hoa hồng tạm giữ', visible: true, required: true },
  { id: 'receivedRevenue', label: 'Hoa hồng rút về', visible: true, required: true },
  { id: 'totalRef', label: 'Tổng Ref', visible: true, required: false },
  { id: 'costPerRef', label: 'Chi phí mỗi Ref', visible: true, required: false },
  { id: 'rateRefPerClick', label: 'Tỷ lệ Ref/Click (%)', visible: true, required: false },
  { id: 'totalFtd', label: 'Số FTD', visible: true, required: false },
  { id: 'costPerFtd', label: 'Chi phí mỗi FTD', visible: true, required: false },
  { id: 'costFtdPerRef', label: 'Tỷ lệ FTD/Ref (%)', visible: true, required: false },
  { id: 'totalTargetDailyKeyVolume', label: 'Volume key/ngày', visible: true, required: false },
  { id: 'totalTargetRef', label: 'Dự tính Ref/ngày', visible: true, required: false },
  { id: 'totalClickPerVolume', label: '% click đạt được', visible: true, required: false },
  { id: 'totalRefPerVolume', label: '% Ref đạt được', visible: true, required: false },
  { id: 'totalCost', label: 'Tổng chi tiêu', visible: true, required: false },
  { id: 'totalClicks', label: 'Tổng lượt click', visible: true, required: false },
  { id: 'totalTargetCpc', label: 'Thầu', visible: true, required: false },
  { id: 'activeCountries', label: 'Quốc gia đang cắn', visible: true, required: false },
  { id: 'actions', label: 'Hành động', visible: true, required: true },
]
