import type { CampaignFormType } from "@/modules/campaign/schemas/campaign-form.schema";
import type { Campaign, UpdateCampaignRequest } from "@/modules/campaign/types/campaign.type";
import { formatDate } from "date-fns";

export const transformCampaignToForm = (campaign?: Campaign): CampaignFormType => ({
  importAt: campaign?.importAt ? new Date(campaign.importAt) : undefined,
  date: campaign?.date ? new Date(campaign.date) : undefined,
  uid: campaign?.uid ?? "",
  mcc: campaign?.mcc ?? "",
  name: campaign?.name ?? "",
  externalId: campaign?.externalId ?? "",
  finalUrlImport: campaign?.finalUrlImport ?? "",
  keywords: campaign?.keywords ?? [],
  topSearchTerms: campaign?.topSearchTerms ?? [],
  status: campaign?.status ?? null,
  avgCpc: campaign?.avgCpc ?? null,
  targetCpc: campaign?.targetCpc ?? null,
  clicks: campaign?.clicks ?? null,
  ctr: campaign?.ctr ?? null,
  cpm: campaign?.cpm ?? null,
  cost: campaign?.cost ?? null,
  targetLocations: campaign?.targetLocations ?? [],
  locationStats: campaign?.locationStats ?? [],
  impression: campaign?.impression ?? null,
  campaignBudget: campaign?.campaignBudget ?? null,
  locationExcluded: campaign?.locationExcluded ?? [],
  negativeKeywords: campaign?.negativeKeywords ?? [],
});

export const transformFormToCampaign = (formData: CampaignFormType): UpdateCampaignRequest => ({
  importAt: formData.importAt ? formatDate(formData.importAt, "yyyy-MM-dd") : null,
  date: formData.date ? formatDate(formData.date, "yyyy-MM-dd") : null,
  uid: formData.uid,
  mcc: formData.mcc,
  name: formData.name,
  externalId: formData.externalId,
  finalUrl: formData.finalUrlImport,
  keywords: formData.keywords.map((k) => ({
    keyword: k.keyword ?? "",
    match: k.match ?? "",
    clicks: k.clicks ?? null,
    ctr: k.ctr ?? null,
    cpc: k.cpc ?? null,
    cpm: k.cpm ?? null,
    cost: k.cost ?? null,
    impression: k.impression ?? null,
    bid: k.bid ?? null,
  })),
  topSearchTerms: formData.topSearchTerms.map((t) => ({
    term: t.term ?? "",
    cpc: t.cpc ?? null,
    cost: t.cost ?? null,
    clicks: t.clicks ?? null,
    ctr: t.ctr ?? null,
    cpm: t.cpm ?? null,
    impression: t.impression ?? null,
  })),
  status: formData.status ?? "",
  avgCpc: formData.avgCpc,
  targetCpc: formData.targetCpc,
  clicks: formData.clicks,
  ctr: formData.ctr,
  cpm: formData.cpm,
  cost: formData.cost,
  targetLocations: formData.targetLocations,
  locationStats: formData.locationStats.map((l) => ({
    location: l.location ?? "",
    clicks: l.clicks ?? null,
    ctr: l.ctr ?? null,
    cpc: l.cpc ?? null,
    cpm: l.cpm ?? null,
    cost: l.cost ?? null,
    impression: l.impression ?? null,
  })),
  impression: formData.impression,
  campaignBudget: formData.campaignBudget,
  locationExcluded: formData.locationExcluded,
  negativeKeywords: formData.negativeKeywords.map((k) => ({
    keyword: k.keyword ?? "",
    match: k.match ?? "",
    clicks: k.clicks ?? null,
    ctr: k.ctr ?? null,
    cpc: k.cpc ?? null,
    cpm: k.cpm ?? null,
    cost: k.cost ?? null,
    impression: k.impression ?? null,
    bid: k.bid ?? null,
  })),
});
