import { APP_PREFIX_PATH, AUTH_PREFIX_PATH } from '@/constants/route.constant'

export const urlConfig = {
  dashboard: `${APP_PREFIX_PATH}/dashboard`,
  taskAssign: `${APP_PREFIX_PATH}/tasks/assign`,
  taskReport: `${APP_PREFIX_PATH}/tasks/reports`,
  customerList: `${APP_PREFIX_PATH}/customers/list`,
  customerUpdate: `${APP_PREFIX_PATH}/customers/update`,
  financeSales: `${APP_PREFIX_PATH}/finances/sales`,
  financeReport: `${APP_PREFIX_PATH}/finances/reports`,
  users: `${APP_PREFIX_PATH}/systems/users`,
  projects: `${APP_PREFIX_PATH}/projects`,
  projectDetail: `${APP_PREFIX_PATH}/projects/detail/:id`,
  logs: `${APP_PREFIX_PATH}/systems/logs`,
  gmailAccounts: `${APP_PREFIX_PATH}/gmail-accounts`,
  gmailAccountDetail: `${APP_PREFIX_PATH}/gmail-accounts/detail/:id`,
  setting: `${APP_PREFIX_PATH}/systems/settings`,
  staffRanking: `${APP_PREFIX_PATH}/staffs/rankings`,
  userUpdateInfo: `${APP_PREFIX_PATH}/update-info`,
  userProfile: `${APP_PREFIX_PATH}/profile`,
  accessDenied: `${APP_PREFIX_PATH}/access-denied`,
  projectTypes: `${APP_PREFIX_PATH}/master-data/project-types`,
  projectStatus: `${APP_PREFIX_PATH}/master-data/project-status`,
  uidStatus: `${APP_PREFIX_PATH}/master-data/uid-status`,
  campaigns: `${APP_PREFIX_PATH}/campaigns`,
  finalUrls: `${APP_PREFIX_PATH}/final-urls`,

  login: `${AUTH_PREFIX_PATH}/login`,
  loginTelegram: `${AUTH_PREFIX_PATH}/telegram`,
}
