export const COLUMN_CONFIG = [
  { id: 'stt', label: 'STT', visible: true, required: true },
  { id: 'importAt', label: 'Ngày nhập', visible: true, required: false },
  { id: 'date', label: 'Dữ liệu ngày', visible: true, required: false },
  { id: 'uid', label: 'UID', visible: true, required: true },
  { id: 'externalId', label: 'ID chiến dịch', visible: true, required: true },
  { id: 'name', label: 'Tên chiến dịch', visible: true, required: true },
  { id: 'finalUrl', label: 'URL', visible: true, required: false },
  { id: 'statusCampaign', label: 'Trạng thái chiến dịch', visible: true, required: false },
  { id: 'mcc', label: 'MCC', visible: false, required: false },
  { id: 'avgCpc', label: 'CPC trung bình', visible: false, required: false },
  { id: 'targetCpc', label: 'Thầu chung', visible: false, required: false },
  { id: 'clicks', label: 'Click', visible: false, required: false },
  { id: 'ctr', label: 'CTR', visible: false, required: false },
  { id: 'cpm', label: 'CPM', visible: false, required: false },
  { id: 'cost', label: 'Ngân sách chi tiêu', visible: false, required: false },
  { id: 'campaignBudget', label: 'Ngân sách chiến dịch', visible: false, required: false },
  { id: 'keywords', label: 'Từ khóa', visible: false, required: false },
  { id: 'negativeKeywords', label: 'Từ khóa không tìm kiếm', visible: false, required: false },
  { id: 'topSearchTerms', label: 'Thuật ngữ tìm kiếm', visible: false, required: false },
  { id: 'targetLocations', label: 'Quốc gia mục tiêu', visible: false, required: false },
  { id: 'locationExcluded', label: 'Quốc gia loại trừ', visible: false, required: false },
  { id: 'locationStats', label: 'Thống kê quốc gia', visible: false, required: false },
  { id: 'actions', label: 'Hành động', visible: true, required: true },
] as const
