export const COLUMN_CONFIG = [
  { id: 'stt', label: 'STT', visible: true, required: true },
  { id: 'name', label: 'Email', visible: true, required: false },
  { id: 'status', label: 'Trạng thái', visible: true, required: false },
  { id: 'creator', label: 'Người tạo', visible: true, required: false },
  { id: 'assignedUsers', label: 'Người nhận mail', visible: true, required: false },
  { id: 'proxy', label: 'Proxy', visible: false, required: false },
  { id: 'password', label: 'Mật khẩu', visible: false, required: false },
  { id: 'recoverMail', label: 'Mail khôi phục', visible: false, required: false },
  { id: 'code2fa', label: 'Mã 2FA', visible: false, required: false },
  { id: 'price', label: 'Giá tiền', visible: false, required: false },
  { id: 'phone', label: 'Số điện thoại', visible: false, required: false },
  { id: 'createdYear', label: 'Năm tạo', visible: false, required: false },
  { id: 'profileName', label: 'Tên hồ sơ', visible: false, required: false },
  { id: 'action', label: 'Hành động', visible: true, required: true },
] as const
